# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cf2f063d8c4d0652d5c206caa48e190127f0e67c3bb2a4943e5aec851c57ffc20eda8e2cc9cebd1326eda8acaf5356a440e67819daf56d9ef531e04336ed715

test:
  secret_key_base: 101f4b83b9e8da200fcf19563ca4c75ad27eb7a570e70b801833e2e784f95c23d4fd93fe47a9dabd372ef14d3f0730eb9c4f57c8878762eda02e9a9ef11d79fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
